version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-training-web:
    image: php:5.6.33-apache-jessie
    container_name:  §§INSTANCE-training-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-lapp-db:training-db
    ports:
      - "§§PORT1:80"
    depends_on:
      - §§INSTANCE-training-db
      - §§INSTANCE-training-data
    volumes_from: 
      - §§INSTANCE-training-data

  §§INSTANCE-training-db:
    image: mysql:5.7
    container_name: §§INSTANCE-training-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusededoutsidethecontainer
      - MYSQL_DATABASE=§§MYSQL_DATABASE_NAME
      - MYSQL_USER=§§MYSQL_DATABASE_USER
      - MYSQL_PASSWORD=§§MYSQL_DATABASE_PASSWORD
    volumes_from: 
      - §§INSTANCE-training-data
    depends_on:
      - §§INSTANCE-training-data

  §§INSTANCE-training-data:
    image: busybox
    container_name: §§INSTANCE-app-data
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./data/var/www/html/:/var/www/html/