version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-container1:
    image: bibbox/app-image
    container_name:  §§INSTANCE-container1
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-lapp-db:app-db
    ports:
      - "§§PORT1:80"
    depends_on:
      - §§INSTANCE-app-db
      - §§INSTANCE-app-data
    volumes_from: 
      - §§INSTANCE-app-data

§§INSTANCE-container2:
  image: bibbox/app-image2
  container_name:  §§INSTANCE-container2
  restart: unless-stopped
  networks:
    - bibbox-default-network
  ports:
    - "§§PORT2:8000"
  depends_on:
    - §§INSTANCE-app-data
  volumes_from: 
    - §§INSTANCE-app-data

  §§INSTANCE-app-db:
    image: mysql:8
    container_name: §§INSTANCE-imagename-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusededoutsidethecontainer
      - MYSQL_DATABASE=§§MYSQL_DATABASE_NAME
      - MYSQL_USER=§§MYSQL_DATABASE_USER
      - MYSQL_PASSWORD=§§MYSQL_DATABASE_PASSWORD
    volumes_from: 
      - §§INSTANCE-app-data
    depends_on:
      - §§INSTANCE-app-data

  §§INSTANCE-app-data:
    image: busybox
    container_name: §§INSTANCE-app-data
    volumes:
      - ./var/app-data:/var/app-data
      - ./var/app-config:/var/app-config