version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-training-web:
    image: wordpress:4.9.3-php5.6-apache
    container_name:  §§INSTANCE-training-web
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-training-db:training-db
    ports:
      - "§§PORT1:80"
    environment:  
      - WORDPRESS_DB_HOST=training-db
      - WORDPRESS_DB_USER=eb3kitlearning
      - WORDPRESS_DB_PASSWORD=tik3be4DB
      - WORDPRESS_DB_NAME=eb3kitlearning
    depends_on:
      - §§INSTANCE-training-db
      - §§INSTANCE-training-data
    volumes_from: 
      - §§INSTANCE-training-data

  §§INSTANCE-training-db:
    image: mysql:5.7
    container_name: §§INSTANCE-training-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=tik3be4DB
      - MYSQL_DATABASE=eb3kitlearning
      - MYSQL_USER=eb3kitlearning
      - MYSQL_PASSWORD=tik3be4DB
      - INSTANCE=§§INSTANCE
    volumes_from: 
      - §§INSTANCE-training-data
    depends_on:
      - §§INSTANCE-training-data

  §§INSTANCE-training-data:
    image: busybox
    container_name: §§INSTANCE-training-data
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
      - ./data/import/import.sh:/docker-entrypoint-initdb.d/import.sh
      - ./data/import/eb3kitlearning.sql:/opt/eb3kitlearning.sql
      - ./data/var/www/html/wp-content:/usr/src/wordpress/wp-content
      - /etc/bibbox/bibbox.cfg:/docker-entrypoint-initdb.d/bibbox.cfg